// Generated by the gRPC protobuf plugin.
// If you make any local change, they will be lost.
// source: yak.proto
#ifndef GRPC_yak_2eproto__INCLUDED
#define GRPC_yak_2eproto__INCLUDED

#include "yak.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace mpc {
namespace yak {

class YakRPC GRPC_FINAL {
 public:
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // exchange
    virtual ::grpc::Status AKE(::grpc::ClientContext* context, const ::mpc::yak::YakMessage& request, ::mpc::yak::YakMessage* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mpc::yak::YakMessage>> AsyncAKE(::grpc::ClientContext* context, const ::mpc::yak::YakMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::mpc::yak::YakMessage>>(AsyncAKERaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::mpc::yak::YakMessage>* AsyncAKERaw(::grpc::ClientContext* context, const ::mpc::yak::YakMessage& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub GRPC_FINAL : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status AKE(::grpc::ClientContext* context, const ::mpc::yak::YakMessage& request, ::mpc::yak::YakMessage* response) GRPC_OVERRIDE;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mpc::yak::YakMessage>> AsyncAKE(::grpc::ClientContext* context, const ::mpc::yak::YakMessage& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::mpc::yak::YakMessage>>(AsyncAKERaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::mpc::yak::YakMessage>* AsyncAKERaw(::grpc::ClientContext* context, const ::mpc::yak::YakMessage& request, ::grpc::CompletionQueue* cq) GRPC_OVERRIDE;
    const ::grpc::RpcMethod rpcmethod_AKE_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // exchange
    virtual ::grpc::Status AKE(::grpc::ServerContext* context, const ::mpc::yak::YakMessage* request, ::mpc::yak::YakMessage* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_AKE : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_AKE() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AKE() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AKE(::grpc::ServerContext* context, const ::mpc::yak::YakMessage* request, ::mpc::yak::YakMessage* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAKE(::grpc::ServerContext* context, ::mpc::yak::YakMessage* request, ::grpc::ServerAsyncResponseWriter< ::mpc::yak::YakMessage>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AKE<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_AKE : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_AKE() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AKE() GRPC_OVERRIDE {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AKE(::grpc::ServerContext* context, const ::mpc::yak::YakMessage* request, ::mpc::yak::YakMessage* response) GRPC_FINAL GRPC_OVERRIDE {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
};

}  // namespace yak
}  // namespace mpc


#endif  // GRPC_yak_2eproto__INCLUDED
