// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: leath.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_leath_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_leath_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/empty.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_leath_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_leath_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_leath_2eproto;
namespace mpc {
class ReconstructReply;
class ReconstructReplyDefaultTypeInternal;
extern ReconstructReplyDefaultTypeInternal _ReconstructReply_default_instance_;
class ReconstructRequestMessage;
class ReconstructRequestMessageDefaultTypeInternal;
extern ReconstructRequestMessageDefaultTypeInternal _ReconstructRequestMessage_default_instance_;
class SearchReply;
class SearchReplyDefaultTypeInternal;
extern SearchReplyDefaultTypeInternal _SearchReply_default_instance_;
class SetupMessage;
class SetupMessageDefaultTypeInternal;
extern SetupMessageDefaultTypeInternal _SetupMessage_default_instance_;
class ShareRequestMessage;
class ShareRequestMessageDefaultTypeInternal;
extern ShareRequestMessageDefaultTypeInternal _ShareRequestMessage_default_instance_;
}  // namespace mpc
PROTOBUF_NAMESPACE_OPEN
template<> ::mpc::ReconstructReply* Arena::CreateMaybeMessage<::mpc::ReconstructReply>(Arena*);
template<> ::mpc::ReconstructRequestMessage* Arena::CreateMaybeMessage<::mpc::ReconstructRequestMessage>(Arena*);
template<> ::mpc::SearchReply* Arena::CreateMaybeMessage<::mpc::SearchReply>(Arena*);
template<> ::mpc::SetupMessage* Arena::CreateMaybeMessage<::mpc::SetupMessage>(Arena*);
template<> ::mpc::ShareRequestMessage* Arena::CreateMaybeMessage<::mpc::ShareRequestMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace mpc {

// ===================================================================

class SetupMessage :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mpc.SetupMessage) */ {
 public:
  SetupMessage();
  virtual ~SetupMessage();

  SetupMessage(const SetupMessage& from);
  SetupMessage(SetupMessage&& from) noexcept
    : SetupMessage() {
    *this = ::std::move(from);
  }

  inline SetupMessage& operator=(const SetupMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline SetupMessage& operator=(SetupMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SetupMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SetupMessage* internal_default_instance() {
    return reinterpret_cast<const SetupMessage*>(
               &_SetupMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(SetupMessage* other);
  friend void swap(SetupMessage& a, SetupMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SetupMessage* New() const final {
    return CreateMaybeMessage<SetupMessage>(nullptr);
  }

  SetupMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SetupMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SetupMessage& from);
  void MergeFrom(const SetupMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SetupMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mpc.SetupMessage";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_leath_2eproto);
    return ::descriptor_table_leath_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes msg = 2;
  void clear_msg();
  static const int kMsgFieldNumber = 2;
  const std::string& msg() const;
  void set_msg(const std::string& value);
  void set_msg(std::string&& value);
  void set_msg(const char* value);
  void set_msg(const void* value, size_t size);
  std::string* mutable_msg();
  std::string* release_msg();
  void set_allocated_msg(std::string* msg);

  // uint64 msg_id = 1;
  void clear_msg_id();
  static const int kMsgIdFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::uint64 msg_id() const;
  void set_msg_id(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // @@protoc_insertion_point(class_scope:mpc.SetupMessage)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_;
  ::PROTOBUF_NAMESPACE_ID::uint64 msg_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_leath_2eproto;
};
// -------------------------------------------------------------------

class ShareRequestMessage :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mpc.ShareRequestMessage) */ {
 public:
  ShareRequestMessage();
  virtual ~ShareRequestMessage();

  ShareRequestMessage(const ShareRequestMessage& from);
  ShareRequestMessage(ShareRequestMessage&& from) noexcept
    : ShareRequestMessage() {
    *this = ::std::move(from);
  }

  inline ShareRequestMessage& operator=(const ShareRequestMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ShareRequestMessage& operator=(ShareRequestMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ShareRequestMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ShareRequestMessage* internal_default_instance() {
    return reinterpret_cast<const ShareRequestMessage*>(
               &_ShareRequestMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ShareRequestMessage* other);
  friend void swap(ShareRequestMessage& a, ShareRequestMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ShareRequestMessage* New() const final {
    return CreateMaybeMessage<ShareRequestMessage>(nullptr);
  }

  ShareRequestMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ShareRequestMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ShareRequestMessage& from);
  void MergeFrom(const ShareRequestMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ShareRequestMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mpc.ShareRequestMessage";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_leath_2eproto);
    return ::descriptor_table_leath_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes value_share = 2;
  void clear_value_share();
  static const int kValueShareFieldNumber = 2;
  const std::string& value_share() const;
  void set_value_share(const std::string& value);
  void set_value_share(std::string&& value);
  void set_value_share(const char* value);
  void set_value_share(const void* value, size_t size);
  std::string* mutable_value_share();
  std::string* release_value_share();
  void set_allocated_value_share(std::string* value_share);

  // bytes mac_share = 3;
  void clear_mac_share();
  static const int kMacShareFieldNumber = 3;
  const std::string& mac_share() const;
  void set_mac_share(const std::string& value);
  void set_mac_share(std::string&& value);
  void set_mac_share(const char* value);
  void set_mac_share(const void* value, size_t size);
  std::string* mutable_mac_share();
  std::string* release_mac_share();
  void set_allocated_mac_share(std::string* mac_share);

  // uint64 value_id = 1;
  void clear_value_id();
  static const int kValueIdFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::uint64 value_id() const;
  void set_value_id(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // @@protoc_insertion_point(class_scope:mpc.ShareRequestMessage)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_share_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr mac_share_;
  ::PROTOBUF_NAMESPACE_ID::uint64 value_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_leath_2eproto;
};
// -------------------------------------------------------------------

class SearchReply :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mpc.SearchReply) */ {
 public:
  SearchReply();
  virtual ~SearchReply();

  SearchReply(const SearchReply& from);
  SearchReply(SearchReply&& from) noexcept
    : SearchReply() {
    *this = ::std::move(from);
  }

  inline SearchReply& operator=(const SearchReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline SearchReply& operator=(SearchReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SearchReply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SearchReply* internal_default_instance() {
    return reinterpret_cast<const SearchReply*>(
               &_SearchReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(SearchReply* other);
  friend void swap(SearchReply& a, SearchReply& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SearchReply* New() const final {
    return CreateMaybeMessage<SearchReply>(nullptr);
  }

  SearchReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SearchReply>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SearchReply& from);
  void MergeFrom(const SearchReply& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SearchReply* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mpc.SearchReply";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_leath_2eproto);
    return ::descriptor_table_leath_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes result = 1;
  void clear_result();
  static const int kResultFieldNumber = 1;
  const std::string& result() const;
  void set_result(const std::string& value);
  void set_result(std::string&& value);
  void set_result(const char* value);
  void set_result(const void* value, size_t size);
  std::string* mutable_result();
  std::string* release_result();
  void set_allocated_result(std::string* result);

  // @@protoc_insertion_point(class_scope:mpc.SearchReply)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr result_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_leath_2eproto;
};
// -------------------------------------------------------------------

class ReconstructRequestMessage :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mpc.ReconstructRequestMessage) */ {
 public:
  ReconstructRequestMessage();
  virtual ~ReconstructRequestMessage();

  ReconstructRequestMessage(const ReconstructRequestMessage& from);
  ReconstructRequestMessage(ReconstructRequestMessage&& from) noexcept
    : ReconstructRequestMessage() {
    *this = ::std::move(from);
  }

  inline ReconstructRequestMessage& operator=(const ReconstructRequestMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReconstructRequestMessage& operator=(ReconstructRequestMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ReconstructRequestMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReconstructRequestMessage* internal_default_instance() {
    return reinterpret_cast<const ReconstructRequestMessage*>(
               &_ReconstructRequestMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(ReconstructRequestMessage* other);
  friend void swap(ReconstructRequestMessage& a, ReconstructRequestMessage& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReconstructRequestMessage* New() const final {
    return CreateMaybeMessage<ReconstructRequestMessage>(nullptr);
  }

  ReconstructRequestMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ReconstructRequestMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ReconstructRequestMessage& from);
  void MergeFrom(const ReconstructRequestMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReconstructRequestMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mpc.ReconstructRequestMessage";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_leath_2eproto);
    return ::descriptor_table_leath_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 value_id = 1;
  void clear_value_id();
  static const int kValueIdFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::uint64 value_id() const;
  void set_value_id(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // @@protoc_insertion_point(class_scope:mpc.ReconstructRequestMessage)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::uint64 value_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_leath_2eproto;
};
// -------------------------------------------------------------------

class ReconstructReply :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:mpc.ReconstructReply) */ {
 public:
  ReconstructReply();
  virtual ~ReconstructReply();

  ReconstructReply(const ReconstructReply& from);
  ReconstructReply(ReconstructReply&& from) noexcept
    : ReconstructReply() {
    *this = ::std::move(from);
  }

  inline ReconstructReply& operator=(const ReconstructReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReconstructReply& operator=(ReconstructReply&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ReconstructReply& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ReconstructReply* internal_default_instance() {
    return reinterpret_cast<const ReconstructReply*>(
               &_ReconstructReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(ReconstructReply* other);
  friend void swap(ReconstructReply& a, ReconstructReply& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ReconstructReply* New() const final {
    return CreateMaybeMessage<ReconstructReply>(nullptr);
  }

  ReconstructReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ReconstructReply>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ReconstructReply& from);
  void MergeFrom(const ReconstructReply& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReconstructReply* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "mpc.ReconstructReply";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_leath_2eproto);
    return ::descriptor_table_leath_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes value_share = 2;
  void clear_value_share();
  static const int kValueShareFieldNumber = 2;
  const std::string& value_share() const;
  void set_value_share(const std::string& value);
  void set_value_share(std::string&& value);
  void set_value_share(const char* value);
  void set_value_share(const void* value, size_t size);
  std::string* mutable_value_share();
  std::string* release_value_share();
  void set_allocated_value_share(std::string* value_share);

  // bytes mac_share = 3;
  void clear_mac_share();
  static const int kMacShareFieldNumber = 3;
  const std::string& mac_share() const;
  void set_mac_share(const std::string& value);
  void set_mac_share(std::string&& value);
  void set_mac_share(const char* value);
  void set_mac_share(const void* value, size_t size);
  std::string* mutable_mac_share();
  std::string* release_mac_share();
  void set_allocated_mac_share(std::string* mac_share);

  // uint64 value_id = 1;
  void clear_value_id();
  static const int kValueIdFieldNumber = 1;
  ::PROTOBUF_NAMESPACE_ID::uint64 value_id() const;
  void set_value_id(::PROTOBUF_NAMESPACE_ID::uint64 value);

  // @@protoc_insertion_point(class_scope:mpc.ReconstructReply)
 private:
  class HasBitSetters;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_share_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr mac_share_;
  ::PROTOBUF_NAMESPACE_ID::uint64 value_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_leath_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SetupMessage

// uint64 msg_id = 1;
inline void SetupMessage::clear_msg_id() {
  msg_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 SetupMessage::msg_id() const {
  // @@protoc_insertion_point(field_get:mpc.SetupMessage.msg_id)
  return msg_id_;
}
inline void SetupMessage::set_msg_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  msg_id_ = value;
  // @@protoc_insertion_point(field_set:mpc.SetupMessage.msg_id)
}

// bytes msg = 2;
inline void SetupMessage::clear_msg() {
  msg_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& SetupMessage::msg() const {
  // @@protoc_insertion_point(field_get:mpc.SetupMessage.msg)
  return msg_.GetNoArena();
}
inline void SetupMessage::set_msg(const std::string& value) {
  
  msg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mpc.SetupMessage.msg)
}
inline void SetupMessage::set_msg(std::string&& value) {
  
  msg_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mpc.SetupMessage.msg)
}
inline void SetupMessage::set_msg(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  msg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mpc.SetupMessage.msg)
}
inline void SetupMessage::set_msg(const void* value, size_t size) {
  
  msg_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mpc.SetupMessage.msg)
}
inline std::string* SetupMessage::mutable_msg() {
  
  // @@protoc_insertion_point(field_mutable:mpc.SetupMessage.msg)
  return msg_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* SetupMessage::release_msg() {
  // @@protoc_insertion_point(field_release:mpc.SetupMessage.msg)
  
  return msg_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void SetupMessage::set_allocated_msg(std::string* msg) {
  if (msg != nullptr) {
    
  } else {
    
  }
  msg_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), msg);
  // @@protoc_insertion_point(field_set_allocated:mpc.SetupMessage.msg)
}

// -------------------------------------------------------------------

// ShareRequestMessage

// uint64 value_id = 1;
inline void ShareRequestMessage::clear_value_id() {
  value_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ShareRequestMessage::value_id() const {
  // @@protoc_insertion_point(field_get:mpc.ShareRequestMessage.value_id)
  return value_id_;
}
inline void ShareRequestMessage::set_value_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  value_id_ = value;
  // @@protoc_insertion_point(field_set:mpc.ShareRequestMessage.value_id)
}

// bytes value_share = 2;
inline void ShareRequestMessage::clear_value_share() {
  value_share_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ShareRequestMessage::value_share() const {
  // @@protoc_insertion_point(field_get:mpc.ShareRequestMessage.value_share)
  return value_share_.GetNoArena();
}
inline void ShareRequestMessage::set_value_share(const std::string& value) {
  
  value_share_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mpc.ShareRequestMessage.value_share)
}
inline void ShareRequestMessage::set_value_share(std::string&& value) {
  
  value_share_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mpc.ShareRequestMessage.value_share)
}
inline void ShareRequestMessage::set_value_share(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  value_share_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mpc.ShareRequestMessage.value_share)
}
inline void ShareRequestMessage::set_value_share(const void* value, size_t size) {
  
  value_share_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mpc.ShareRequestMessage.value_share)
}
inline std::string* ShareRequestMessage::mutable_value_share() {
  
  // @@protoc_insertion_point(field_mutable:mpc.ShareRequestMessage.value_share)
  return value_share_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ShareRequestMessage::release_value_share() {
  // @@protoc_insertion_point(field_release:mpc.ShareRequestMessage.value_share)
  
  return value_share_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ShareRequestMessage::set_allocated_value_share(std::string* value_share) {
  if (value_share != nullptr) {
    
  } else {
    
  }
  value_share_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value_share);
  // @@protoc_insertion_point(field_set_allocated:mpc.ShareRequestMessage.value_share)
}

// bytes mac_share = 3;
inline void ShareRequestMessage::clear_mac_share() {
  mac_share_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ShareRequestMessage::mac_share() const {
  // @@protoc_insertion_point(field_get:mpc.ShareRequestMessage.mac_share)
  return mac_share_.GetNoArena();
}
inline void ShareRequestMessage::set_mac_share(const std::string& value) {
  
  mac_share_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mpc.ShareRequestMessage.mac_share)
}
inline void ShareRequestMessage::set_mac_share(std::string&& value) {
  
  mac_share_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mpc.ShareRequestMessage.mac_share)
}
inline void ShareRequestMessage::set_mac_share(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  mac_share_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mpc.ShareRequestMessage.mac_share)
}
inline void ShareRequestMessage::set_mac_share(const void* value, size_t size) {
  
  mac_share_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mpc.ShareRequestMessage.mac_share)
}
inline std::string* ShareRequestMessage::mutable_mac_share() {
  
  // @@protoc_insertion_point(field_mutable:mpc.ShareRequestMessage.mac_share)
  return mac_share_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ShareRequestMessage::release_mac_share() {
  // @@protoc_insertion_point(field_release:mpc.ShareRequestMessage.mac_share)
  
  return mac_share_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ShareRequestMessage::set_allocated_mac_share(std::string* mac_share) {
  if (mac_share != nullptr) {
    
  } else {
    
  }
  mac_share_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), mac_share);
  // @@protoc_insertion_point(field_set_allocated:mpc.ShareRequestMessage.mac_share)
}

// -------------------------------------------------------------------

// SearchReply

// bytes result = 1;
inline void SearchReply::clear_result() {
  result_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& SearchReply::result() const {
  // @@protoc_insertion_point(field_get:mpc.SearchReply.result)
  return result_.GetNoArena();
}
inline void SearchReply::set_result(const std::string& value) {
  
  result_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mpc.SearchReply.result)
}
inline void SearchReply::set_result(std::string&& value) {
  
  result_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mpc.SearchReply.result)
}
inline void SearchReply::set_result(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  result_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mpc.SearchReply.result)
}
inline void SearchReply::set_result(const void* value, size_t size) {
  
  result_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mpc.SearchReply.result)
}
inline std::string* SearchReply::mutable_result() {
  
  // @@protoc_insertion_point(field_mutable:mpc.SearchReply.result)
  return result_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* SearchReply::release_result() {
  // @@protoc_insertion_point(field_release:mpc.SearchReply.result)
  
  return result_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void SearchReply::set_allocated_result(std::string* result) {
  if (result != nullptr) {
    
  } else {
    
  }
  result_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), result);
  // @@protoc_insertion_point(field_set_allocated:mpc.SearchReply.result)
}

// -------------------------------------------------------------------

// ReconstructRequestMessage

// uint64 value_id = 1;
inline void ReconstructRequestMessage::clear_value_id() {
  value_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ReconstructRequestMessage::value_id() const {
  // @@protoc_insertion_point(field_get:mpc.ReconstructRequestMessage.value_id)
  return value_id_;
}
inline void ReconstructRequestMessage::set_value_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  value_id_ = value;
  // @@protoc_insertion_point(field_set:mpc.ReconstructRequestMessage.value_id)
}

// -------------------------------------------------------------------

// ReconstructReply

// uint64 value_id = 1;
inline void ReconstructReply::clear_value_id() {
  value_id_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 ReconstructReply::value_id() const {
  // @@protoc_insertion_point(field_get:mpc.ReconstructReply.value_id)
  return value_id_;
}
inline void ReconstructReply::set_value_id(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  value_id_ = value;
  // @@protoc_insertion_point(field_set:mpc.ReconstructReply.value_id)
}

// bytes value_share = 2;
inline void ReconstructReply::clear_value_share() {
  value_share_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ReconstructReply::value_share() const {
  // @@protoc_insertion_point(field_get:mpc.ReconstructReply.value_share)
  return value_share_.GetNoArena();
}
inline void ReconstructReply::set_value_share(const std::string& value) {
  
  value_share_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mpc.ReconstructReply.value_share)
}
inline void ReconstructReply::set_value_share(std::string&& value) {
  
  value_share_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mpc.ReconstructReply.value_share)
}
inline void ReconstructReply::set_value_share(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  value_share_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mpc.ReconstructReply.value_share)
}
inline void ReconstructReply::set_value_share(const void* value, size_t size) {
  
  value_share_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mpc.ReconstructReply.value_share)
}
inline std::string* ReconstructReply::mutable_value_share() {
  
  // @@protoc_insertion_point(field_mutable:mpc.ReconstructReply.value_share)
  return value_share_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ReconstructReply::release_value_share() {
  // @@protoc_insertion_point(field_release:mpc.ReconstructReply.value_share)
  
  return value_share_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ReconstructReply::set_allocated_value_share(std::string* value_share) {
  if (value_share != nullptr) {
    
  } else {
    
  }
  value_share_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value_share);
  // @@protoc_insertion_point(field_set_allocated:mpc.ReconstructReply.value_share)
}

// bytes mac_share = 3;
inline void ReconstructReply::clear_mac_share() {
  mac_share_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline const std::string& ReconstructReply::mac_share() const {
  // @@protoc_insertion_point(field_get:mpc.ReconstructReply.mac_share)
  return mac_share_.GetNoArena();
}
inline void ReconstructReply::set_mac_share(const std::string& value) {
  
  mac_share_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:mpc.ReconstructReply.mac_share)
}
inline void ReconstructReply::set_mac_share(std::string&& value) {
  
  mac_share_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:mpc.ReconstructReply.mac_share)
}
inline void ReconstructReply::set_mac_share(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  mac_share_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:mpc.ReconstructReply.mac_share)
}
inline void ReconstructReply::set_mac_share(const void* value, size_t size) {
  
  mac_share_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:mpc.ReconstructReply.mac_share)
}
inline std::string* ReconstructReply::mutable_mac_share() {
  
  // @@protoc_insertion_point(field_mutable:mpc.ReconstructReply.mac_share)
  return mac_share_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* ReconstructReply::release_mac_share() {
  // @@protoc_insertion_point(field_release:mpc.ReconstructReply.mac_share)
  
  return mac_share_.ReleaseNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void ReconstructReply::set_allocated_mac_share(std::string* mac_share) {
  if (mac_share != nullptr) {
    
  } else {
    
  }
  mac_share_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), mac_share);
  // @@protoc_insertion_point(field_set_allocated:mpc.ReconstructReply.mac_share)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace mpc

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_leath_2eproto
